#!/bin/bash

# z_certbot-haproxy-post-renewal

# setup certbot in standalone mode using port :10000
# use HAProxy to front /.well-known/acme-challenge to :10000
# https://certbot.eff.org/docs/using.html#standalone

# set certificate domain name
DOMAIN="my-domain.com"

# path to live certificates
LIVE="/etc/letsencrypt/live"

# haproxy certs location
HA="/etc/haproxy/certs"

# use 'certbot certificates' command to list
FC="${LIVE}/${DOMAIN}/fullchain.pem"
PK="${LIVE}/${DOMAIN}/privkey.pem"

cat ${FC} ${PK} > ${HA}/${DOMAIN}.pem

systemctl restart haproxy

# To Deploy
# can drop into /etc/cron.daily/certbot-haproxy-post-renewal
# OR /etc/letsencrypt/renewal-hooks/post/certbot-haproxy-post-renewal
# as in https://certbot.eff.org/docs/using.html#renewing-certificates
