#!/usr/bin/env bash

# DIRS: array of directories that contains daily backup
# THRESHOLD: any thing more than this threshold will be purged
#    e.g. if it is daily backup then this equate any backup older than 36 days
#
declare -a DIRS=(/backup/app /backup/db /backup/content)
THRESHOLD=36

for DIR in "${DIRS[@]}"
do
    CNT=`ls -rt ${DIR} | wc -l`

    if [[ ${CNT} -gt ${THRESHOLD} ]]; then
        cd ${DIR} && ls -tp ${DIR} | grep -v '/$' | tail -n +${THRESHOLD} | xargs -d '\n' -r rm --
    fi

done
